/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiPublicAuthLogoutRouteImport } from './routes/api/public/auth.logout'
import { Route as ApiPublicAuthMeRouteImport } from './routes/api/public/auth.me'
import { Route as ApiPublicAuthSalesforceRouteImport } from './routes/api/public/auth.salesforce'
import { Route as ApiPublicSalesforceObjectRouteImport } from './routes/api/public/salesforce.$object'
import { Route as ApiPublicAuthSalesforceCallbackRouteImport } from './routes/api/public/auth.salesforce.callback'
import { Route as ApiPublicSalesforceObjectIdRouteImport } from './routes/api/public/salesforce.$object.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLogoutRoute = ApiPublicAuthLogoutRouteImport.update({
  id: '/api/public/auth/logout',
  path: '/api/public/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthMeRoute = ApiPublicAuthMeRouteImport.update({
  id: '/api/public/auth/me',
  path: '/api/public/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSalesforceRoute = ApiPublicAuthSalesforceRouteImport.update({
  id: '/api/public/auth/salesforce',
  path: '/api/public/auth/salesforce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSalesforceObjectRoute =
  ApiPublicSalesforceObjectRouteImport.update({
    id: '/api/public/salesforce/$object',
    path: '/api/public/salesforce/$object',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthSalesforceCallbackRoute =
  ApiPublicAuthSalesforceCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiPublicAuthSalesforceRoute,
  } as any)
const ApiPublicSalesforceObjectIdRoute =
  ApiPublicSalesforceObjectIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicSalesforceObjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/api/public/auth/me': typeof ApiPublicAuthMeRoute
  '/api/public/auth/salesforce': typeof ApiPublicAuthSalesforceRouteWithChildren
  '/api/public/salesforce/$object': typeof ApiPublicSalesforceObjectRouteWithChildren
  '/api/public/auth/salesforce/callback': typeof ApiPublicAuthSalesforceCallbackRoute
  '/api/public/salesforce/$object/$id': typeof ApiPublicSalesforceObjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/api/public/auth/me': typeof ApiPublicAuthMeRoute
  '/api/public/auth/salesforce': typeof ApiPublicAuthSalesforceRouteWithChildren
  '/api/public/salesforce/$object': typeof ApiPublicSalesforceObjectRouteWithChildren
  '/api/public/auth/salesforce/callback': typeof ApiPublicAuthSalesforceCallbackRoute
  '/api/public/salesforce/$object/$id': typeof ApiPublicSalesforceObjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/api/public/auth/me': typeof ApiPublicAuthMeRoute
  '/api/public/auth/salesforce': typeof ApiPublicAuthSalesforceRouteWithChildren
  '/api/public/salesforce/$object': typeof ApiPublicSalesforceObjectRouteWithChildren
  '/api/public/auth/salesforce/callback': typeof ApiPublicAuthSalesforceCallbackRoute
  '/api/public/salesforce/$object/$id': typeof ApiPublicSalesforceObjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/public/auth/logout'
    | '/api/public/auth/me'
    | '/api/public/auth/salesforce'
    | '/api/public/salesforce/$object'
    | '/api/public/auth/salesforce/callback'
    | '/api/public/salesforce/$object/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/public/auth/logout'
    | '/api/public/auth/me'
    | '/api/public/auth/salesforce'
    | '/api/public/salesforce/$object'
    | '/api/public/auth/salesforce/callback'
    | '/api/public/salesforce/$object/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/public/auth/logout'
    | '/api/public/auth/me'
    | '/api/public/auth/salesforce'
    | '/api/public/salesforce/$object'
    | '/api/public/auth/salesforce/callback'
    | '/api/public/salesforce/$object/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiPublicAuthLogoutRoute: typeof ApiPublicAuthLogoutRoute
  ApiPublicAuthMeRoute: typeof ApiPublicAuthMeRoute
  ApiPublicAuthSalesforceRoute: typeof ApiPublicAuthSalesforceRouteWithChildren
  ApiPublicSalesforceObjectRoute: typeof ApiPublicSalesforceObjectRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/logout': {
      id: '/api/public/auth/logout'
      path: '/api/public/auth/logout'
      fullPath: '/api/public/auth/logout'
      preLoaderRoute: typeof ApiPublicAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/me': {
      id: '/api/public/auth/me'
      path: '/api/public/auth/me'
      fullPath: '/api/public/auth/me'
      preLoaderRoute: typeof ApiPublicAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/salesforce': {
      id: '/api/public/auth/salesforce'
      path: '/api/public/auth/salesforce'
      fullPath: '/api/public/auth/salesforce'
      preLoaderRoute: typeof ApiPublicAuthSalesforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/salesforce/$object': {
      id: '/api/public/salesforce/$object'
      path: '/api/public/salesforce/$object'
      fullPath: '/api/public/salesforce/$object'
      preLoaderRoute: typeof ApiPublicSalesforceObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/salesforce/callback': {
      id: '/api/public/auth/salesforce/callback'
      path: '/callback'
      fullPath: '/api/public/auth/salesforce/callback'
      preLoaderRoute: typeof ApiPublicAuthSalesforceCallbackRouteImport
      parentRoute: typeof ApiPublicAuthSalesforceRoute
    }
    '/api/public/salesforce/$object/$id': {
      id: '/api/public/salesforce/$object/$id'
      path: '/$id'
      fullPath: '/api/public/salesforce/$object/$id'
      preLoaderRoute: typeof ApiPublicSalesforceObjectIdRouteImport
      parentRoute: typeof ApiPublicSalesforceObjectRoute
    }
  }
}

interface ApiPublicAuthSalesforceRouteChildren {
  ApiPublicAuthSalesforceCallbackRoute: typeof ApiPublicAuthSalesforceCallbackRoute
}

const ApiPublicAuthSalesforceRouteChildren: ApiPublicAuthSalesforceRouteChildren =
  {
    ApiPublicAuthSalesforceCallbackRoute: ApiPublicAuthSalesforceCallbackRoute,
  }

const ApiPublicAuthSalesforceRouteWithChildren =
  ApiPublicAuthSalesforceRoute._addFileChildren(
    ApiPublicAuthSalesforceRouteChildren,
  )

interface ApiPublicSalesforceObjectRouteChildren {
  ApiPublicSalesforceObjectIdRoute: typeof ApiPublicSalesforceObjectIdRoute
}

const ApiPublicSalesforceObjectRouteChildren: ApiPublicSalesforceObjectRouteChildren =
  {
    ApiPublicSalesforceObjectIdRoute: ApiPublicSalesforceObjectIdRoute,
  }

const ApiPublicSalesforceObjectRouteWithChildren =
  ApiPublicSalesforceObjectRoute._addFileChildren(
    ApiPublicSalesforceObjectRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiPublicAuthLogoutRoute: ApiPublicAuthLogoutRoute,
  ApiPublicAuthMeRoute: ApiPublicAuthMeRoute,
  ApiPublicAuthSalesforceRoute: ApiPublicAuthSalesforceRouteWithChildren,
  ApiPublicSalesforceObjectRoute: ApiPublicSalesforceObjectRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
